name:                persistent-firebase
version:             0.1.0.0
github:              "patrotom/persistent-firebase"
license:             MIT
author:              "Tomáš Patro"
maintainer:          "tomas.patro@gmail.com"
copyright:           "Copyright 2020 Tomas Patro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/patrotom/persistent-firebase#readme>

dependencies:
- base >= 4.7 && < 5
- req
- text
- aeson
- http-api-data
- http-conduit
- bytestring

library:
  source-dirs: src

tests:
  persistent-firebase-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - persistent-firebase
    - hspec
