name:                persistent-firebase
version:             0.1.0.0
github:              "patrotom/persistent-firebase"
license:             BSD3
author:              "Tomas Patro"
maintainer:          "tomas.patro@gmail.com"
copyright:           "Copyright 2018 Tomas Patro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/patrotom/persistent-firebase#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  persistent-firebase-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - persistent-firebase

tests:
  persistent-firebase-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - persistent-firebase
