name:                firebase-haskell
version:             0.0.1
github:              "patrotom/firebase-haskell"
license:             MIT
author:              "Tomas Patro"
maintainer:          "tomas.patro@gmail.com"
copyright:           "Copyright 2020 Tomas Patro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/patrotom/firebase-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- http-api-data
- http-conduit
- bytestring
- http-client

library:
  source-dirs: src

tests:
  firebase-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firebase-haskell
    - hspec
    - http-conduit
    - http-client
    - bytestring
